// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/asarturas/adventofcode/day05/solution (interfaces: Evaluator)

package solution

import (
	gomock "github.com/asarturas/adventofcode/Godeps/_workspace/src/github.com/golang/mock/gomock"
)

// Mock of Evaluator interface
type MockEvaluator struct {
	ctrl     *gomock.Controller
	recorder *_MockEvaluatorRecorder
}

// Recorder for MockEvaluator (not exported)
type _MockEvaluatorRecorder struct {
	mock *MockEvaluator
}

func NewMockEvaluator(ctrl *gomock.Controller) *MockEvaluator {
	mock := &MockEvaluator{ctrl: ctrl}
	mock.recorder = &_MockEvaluatorRecorder{mock}
	return mock
}

func (_m *MockEvaluator) EXPECT() *_MockEvaluatorRecorder {
	return _m.recorder
}

func (_m *MockEvaluator) IsNice(_param0 string) bool {
	ret := _m.ctrl.Call(_m, "IsNice", _param0)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockEvaluatorRecorder) IsNice(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "IsNice", arg0)
}
