// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/asarturas/adventofcode/day04/solution (interfaces: Hasher)

package solution

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Hasher interface
type MockHasher struct {
	ctrl     *gomock.Controller
	recorder *_MockHasherRecorder
}

// Recorder for MockHasher (not exported)
type _MockHasherRecorder struct {
	mock *MockHasher
}

func NewMockHasher(ctrl *gomock.Controller) *MockHasher {
	mock := &MockHasher{ctrl: ctrl}
	mock.recorder = &_MockHasherRecorder{mock}
	return mock
}

func (_m *MockHasher) EXPECT() *_MockHasherRecorder {
	return _m.recorder
}

func (_m *MockHasher) Hash(_param0 string, _param1 int) string {
	ret := _m.ctrl.Call(_m, "Hash", _param0, _param1)
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockHasherRecorder) Hash(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Hash", arg0, arg1)
}
